variables:
  - group: EmonsProjects.Common.Configurations
  - group: VocRise.Dev.Configurations
  - group: VocRise.DictionaryService.Configurations
  

resources:
  containers:
  - container:

trigger: none

pr: none

pool:
  name: Azure Pipelines
  vmImage: ubuntu-latest

steps:
  - task: AzureWebAppContainer@1
    displayName: 'Azure Web App on Container Deploy'
    inputs:
      azureSubscription: RiseVocab Dev Resource Manager
      appName: risevocab-dev-dictionary-service
      containers: emonsprojects.azurecr.io/risevocab/dictionaryservice:latest'
      # appSettings: '-DOCKER_REGISTRY_SERVER_URL $(EmonsProjects.ContainerRegistryUrl) -DOCKER_REGISTRY_SERVER_USERNAME $(EmonsProjects.ContainerRegistryUsername) -DOCKER_REGISTRY_SERVER_PASSWORD $(registryPassword) -WEBSITES_PORT 80:4000'
