variables:
  - group: RiseVocab.Common.Configurations
  - group: RiseVocab.Dev.Configurations
  - group: RiseVocab.DictionaryService.Configurations

resources:
  containers:
  - container: ContainerImage
    image: code2learn.azurecr.io/risevocab/dictionary-service:latest

trigger: none

pr: none

pool:
  name: Azure Pipelines
  vmImage: ubuntu-latest

jobs:
- deployment:
  displayName: Deploy App Service
  environment: $(RiseVocab.Environment)
  strategy:
    runOnce:
      deploy:
        steps:
        - task: AzureWebAppContainer@1
          displayName: Deploy Azure Web App on Container
          inputs:
            appName: $(RiseVocab.AppServiceName)
            azureSubscription: $(RiseVocab.AzureConnection)
            imageName: ContainerImage
            appSettings: |
             -RiseVocab.Database.ConnectionString $(RiseVocab.Database.ConnectionString) 
             -RiseVocab.Port 80
